### ISSUE TITLE
Define data model

### ISSUE THREAD

**Issue by cjimenezsanchez** [fesave/AAC-Board#28]
Define data models to be used in the application.

Define Dashboard, Cell and Pictogram models.

**Comment by cjimenezsanchez** [comment]
Proposal for domain and data models:

**DOMAIN**

**Dashboard**

```kotlin

data class Dashboard(
    val id: Int,
    val name: String,
    val rows: Int,
    val columns: Int,
    val cells: List<DashboardCell>
)

``` 


**DashboardCell**

```kotlin

data class DashboardCell(
    val dashboardId: Int,
    val i: Int,
    val j: Int,
    val pictogram: Pictogram?
)

```

**Pictogram**

```kotlin

data class Pictogram(
    val id: Int,
    val keyword: String,
    val url: String
)

```

**DATA**

**Dashboard entity**

```kotlin

data class DashboardEntity(
    @PrimaryKey 
    val id: Int,
    val name: String,
    val rows: Int,
    val columns: Int
)

```

**DashboardCell entity**

```kotlin

 data class DashboardCellEntity(
    val dashboardId: Int,  //Composed primary key from dashboardId,  i and j
    val i: Int,
    val j: Int,
    val pictogramId: Int? //null when no pictogram associated to board cell
)

```

**PictogramEntity**

```kotlin 

data class Pictogram(
    @PrimaryKey val id: Int,
    val keyword: String,
    val url: String
)

```

**Comment by cjimenezsanchez** [comment]
@jmgjmg @fesave check the proposal for the data and domain models for the application. I have chosen to decouple the pictograms models from the dashboard and cells in order to be able to reuse pictograms in other dashboards (open for discussion).

**Comment by jmgjmg** [comment]
I am not sure about decoupling pictograms in a separate table/entity. It makes the model a bit more complex and, additionally, we should add a new feature to "share" or reuse pictograms. The text should be associated with the cell (or at least the cell should be allowed to store a different text from the pictogram).

**Comment by fesave** [comment]
I think it is a good starting point to begin with, but I think there are certain fields that could be more explanatory with their name, for example the "j" and "i" fields I would rename them by adding "coordinate" as a prefix. I would even rename them to X and Y. How do you see it?
