### ISSUE TITLE
Create and document App flow

### ISSUE THREAD

**Issue by fesave** [fesave/AAC-Board#3]

**Comment by jmgjmg** [comment]
Flujo tentativo de la aplicación con un skecth a mano de las distintas pantallas. 
Al final he dejado el menú tradicional pues no hace falta más que una opción para abrir la pantalla de tableros (podemos redefinirlo cómo y dónde queramos)
![aacboard_1](https://user-images.githubusercontent.com/1650863/226437325-f09c07d9-7932-4ddb-9c45-1c19bde136f8.png)
![aacboard_2](https://user-images.githubusercontent.com/1650863/226437332-875ebf1c-a69e-4e24-9e7b-b23abea500d0.png)

**Comment by jmgjmg** [comment]
Habría que añadir en la pantalla principal un botón adicional para borrar el "texto" de entrada

**Comment by jmgjmg** [comment]
Update hand-drawn pictures and add create the first version of the wiki with it
